version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sparkflow-lambdas"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mus9pokbl5xy"
s3_prefix = "sparkflow-lambdas"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
