AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SparkFlow EMR utilities

Resources:
  SparkflowLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: [ 'sts:AssumeRole' ]
            Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action: [ 'sqs:*', 'dynamodb:*', 'ec2:*' ]
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: SparkflowLambdaRole



  # Function for creating and deleting EMR clusters
  ClusterManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sparkflowemr/
      Handler: cluster_manager.cluster_manager
      Runtime: python3.7
      Timeout: 600
      Role: !GetAtt SparkflowLambdaRole.Arn

  # Function for polling steps on EMR clusters
  ClusterPollerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sparkflowemr/
      Handler: cluster_poller.cluster_poller
      Runtime: python3.7
      Timeout: 600
      Role: !GetAtt SparkflowLambdaRole.Arn

  # Function for submitting steps
  StepManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sparkflowemr/
      Handler: step_manager.step_manager
      Runtime: python3.7
      Timeout: 600
      Role: !GetAtt SparkflowLambdaRole.Arn
